language: generic
services:
  - docker

before_install:
  - docker build -t mayank266/test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mayank266/test npm test

after_success:
  - docker build -t mayank266/multi-client ./client
  - docker build -t mayank266/multi-nginx ./nginx
  - docker build -t mayank266/multi-server ./server
  - docker build -t mayank266/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push mayank266/multi-client
  - docker push mayank266/multi-nginx
  - docker push mayank266/multi-server
  - docker push mayank266/multi-worker